version: "3.9"
services:
    pkg:
        build: .
        ports:
            - "0.0.0.0:5999:5999"
        networks:
            - qbreak-network

networks:
    qbreak-network:
        external: true